### ISSUE TITLE
Changes needed

### ISSUE THREAD

**Issue by louisetang88** [AlanChen4/beatcode#3]
- fix problem model so that multiple categories can be assigned to one problem
- add redirect for anonymous users 
- rename category model attribute "category" to "name"
- fix views after above changes are made
- add default url (should be home)
- remove last done attribute on category model

**Comment by AlanChen4** [comment]
Add fix for
- add redirect for anonymous users
- add default url (should be home)

**Comment by AlanChen4** [comment]
Added all fixes
